/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ACER
 */
public class SinhVien_Panel extends javax.swing.JPanel {

    /**
     * Creates new form SinhVien_Panel
     */
    public SinhVien_Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbt_themMoi = new javax.swing.JToggleButton();
        jtf_Search_HocVien = new javax.swing.JTextField();
        jpn_View_HocVien = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 153));

        jbt_themMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt_themMoi.setText("+ Thêm mới");
        jbt_themMoi.setBorder(null);
        jbt_themMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_themMoiActionPerformed(evt);
            }
        });

        jtf_Search_HocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Search_HocVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpn_View_HocVienLayout = new javax.swing.GroupLayout(jpn_View_HocVien);
        jpn_View_HocVien.setLayout(jpn_View_HocVienLayout);
        jpn_View_HocVienLayout.setHorizontalGroup(
            jpn_View_HocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpn_View_HocVienLayout.setVerticalGroup(
            jpn_View_HocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 408, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpn_View_HocVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtf_Search_HocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                        .addComponent(jbt_themMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_Search_HocVien, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jbt_themMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jpn_View_HocVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_themMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_themMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_themMoiActionPerformed

    private void jtf_Search_HocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Search_HocVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Search_HocVienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jbt_themMoi;
    private javax.swing.JPanel jpn_View_HocVien;
    private javax.swing.JTextField jtf_Search_HocVien;
    // End of variables declaration//GEN-END:variables
}
